//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Danovy_Urad
    {
        public string Id { get; set; }
        public string Ic_Dph { get; set; }
        public string Meno { get; set; }
        public string Mesto { get; set; }
        public string PSC { get; set; }
        public string Adresa { get; set; }
        public Nullable<int> Rok_Porusenia { get; set; }
        public Nullable<int> Ico { get; set; }
        public Nullable<System.DateTime> Datum_Porusenia { get; set; }
        public Nullable<System.DateTime> Datum_Aktualizacie { get; set; }
    }
}
