//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KurzovyListok
    {
        public string GuidID { get; set; }
        public string Mena { get; set; }
        public Nullable<decimal> Kurz { get; set; }
        public Nullable<System.DateTime> DatumAktualizacie { get; set; }
    }
}
