//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Socialna_Poistovna
    {
        public int Id { get; set; }
        public string GuidID { get; set; }
        public string MenoFirmy { get; set; }
        public string Adresa { get; set; }
        public string Mesto { get; set; }
        public Nullable<decimal> DlznaSuma { get; set; }
        public Nullable<System.DateTime> DatumAktualizacie { get; set; }
    }
}
