//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zp_Union
    {
        public string GuidID { get; set; }
        public string Meno { get; set; }
        public string Mesto { get; set; }
        public string Ulica { get; set; }
        public string PSC { get; set; }
        public string ICO { get; set; }
        public Nullable<decimal> Dlzna_Suma { get; set; }
        public string Typ_Starostlivosti { get; set; }
        public Nullable<System.DateTime> Datum_Aktualizacie { get; set; }
    }
}
